# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "restapi_doc"
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kevin Haight"]
  s.date = "2012-05-15"
  s.description = "REST API doc generates an easy way to create a twitter style document for your RESTful interface.  \n                        Leveraging Twitter Bootstrap to create an easy to read document for your RESTful api. "
  s.email = "kevinjhaight@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "CHANGELOG.rdoc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/restapi_doc.rb",
    "lib/restapi_doc/config.rb",
    "lib/restapi_doc/config/restapi_doc.yml",
    "lib/restapi_doc/method_doc.rb",
    "lib/restapi_doc/railtie.rb",
    "lib/restapi_doc/resource_doc.rb",
    "lib/restapi_doc/tasks/restapi_doc_tasks.rake",
    "lib/restapi_doc/template/assets/css/bootstrap-responsive.min.css",
    "lib/restapi_doc/template/assets/css/bootstrap.less",
    "lib/restapi_doc/template/assets/css/bootstrap.min.css",
    "lib/restapi_doc/template/assets/css/prettify.css",
    "lib/restapi_doc/template/assets/img/glyphicons-halflings-white.png",
    "lib/restapi_doc/template/assets/img/glyphicons-halflings.png",
    "lib/restapi_doc/template/assets/js/bootstrap.min.js",
    "lib/restapi_doc/template/assets/js/jquery.js",
    "lib/restapi_doc/template/assets/js/less.min.js",
    "lib/restapi_doc/template/assets/js/prettify.js",
    "lib/restapi_doc/template/detail.html.haml",
    "lib/restapi_doc/template/index.html.haml",
    "restapi_doc.gemspec"
  ]
  s.homepage = "http://github.com/alayho/restapi_doc"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.17"
  s.summary = "REST API doc generates an easy way to create a twitter style document for your RESTful interface"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 2.1"])
      s.add_runtime_dependency(%q<haml>, ["= 3.1.4"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.2.0"])
      s.add_development_dependency(%q<mocha>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 2.1"])
      s.add_dependency(%q<haml>, ["= 3.1.4"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.2.0"])
      s.add_dependency(%q<mocha>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 2.1"])
    s.add_dependency(%q<haml>, ["= 3.1.4"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.2.0"])
    s.add_dependency(%q<mocha>, [">= 0"])
  end
end

